const publicPhoto = (filename: string) => `${import.meta.env.BASE_URL}${encodeURIComponent(filename)}`

export const content = {
  hero: {
    eyebrow: 'A little surprise, sent with all my love',
    titlePrefix: 'A little',
    titleHighlight: 'surprise',
    titleLine: 'for you,',
    titleEnding: 'from miles away.',
    subtitle: 'I wish I could be there to see your smile as you open this. Until I can hold you again, here is a little world I made just for you — filled with our memories and everything I miss about us.',
    cta: 'Unwrap your surprise',
    image: { src: publicPhoto('Front-Cover.jpeg'), alt: 'Our cover memory' },
  },
  counter: {
    startDate: '2026-08-13',
    eyebrow: '03 / choosing you, every day',
    title: 'Every day, I’m',
    titleHighlight: 'still choosing you.',
    description: 'These are the days of us — the ones spent close and the ones spent missing each other. Every one of them means more because I get to love you.',
  },
  timeline: [
    { date: 'BITS Pilani', title: 'Jaha se start hua tha', description: 'Thank you uss din humse baat karne ke liye aur congratulations humko ki itna sweet aur loyal insaan meri zindagi mein aaya.', image: publicPhoto('First.jpeg') },
    { date: 'BITS Pilani (part - 2)', title: 'Best-Friend above all', description: 'Jitne bhi BITS mein memory bane, bhaii sab ke sab amazing the, best sabse, humari shart ki kaun raat bhar jagega (tum jeeti thi par thik hai jo bhi).', image: publicPhoto('Second.jpeg') },
    { date: 'City Visits', title: 'City chalte hai guyss', description: 'Bhai har baar last moment city jana, tumhara overthink karna isme bhi, but tab bhi akhri mein chalne lagna sabke saath. Maybe yehi se physical bond strong hua hai humara, again bahut important step.', image: publicPhoto('Third.jpeg') },
    { date: 'Holi', title: 'Holi and Trip', description: 'Holi khelna saath mein and just some random plans and we are in Pipariya, humari pehli trip, humari pehli bike ride, tumhara mere ghar pe pehli baar ana, crazyyy bhaiii', image: publicPhoto('Fourth.jpeg') },
    { date: 'Footloose Party', title: 'Ladai Jhagada', description: 'Comfortable hona start hogaya hai ki maaro ek dusre ko, aur tumhara choti choti baat pe gusana, ("nhi kheechwaungi apke saath photo")', image: publicPhoto('Fifth.jpeg') },
    { date: 'Footloose Party (part - 2)', title: 'We look cute', description: 'Par tabhi humlog kheechwaye saath mein photo, pyaar toh tum bahut karti ho humse, man jati ho sab mera, Love youu yaarrrrr❤️.', image: publicPhoto('Sixth.jpeg') },
    { date: 'Lunch or Dinner', title: 'Kya Khana hai?', description: 'Sabse imp. question ki khana kya hai, aur har din ispe behas karna, par iss din baal banaye the tumhara pehli baar😁.', image: publicPhoto('Seventh.jpeg') },
    { date: 'Fights', title: 'Ladai Jhagda (part - 2)', description: 'again ladai almost har photo mein laad hi reh hote hai, kyu karti ho itne bestie taraeke behave thoda toh girlfriend jaise karo.', image: publicPhoto('Eighth.jpeg') },
    { date: 'BESTTTTTTTTT💝', title: 'The Day it happened', description: 'The day everything changed for the better, tumhara confess karna mera propose karna sabkuch best tha bhaii, now i have most wonderful GF😁.', image: publicPhoto('Ninth.jpeg') },
    { date: 'Intern🙃', title: 'Long Distance', description: 'So current state of us, but i gurrantee that it will end soon.', image: publicPhoto('Tenth.jpeg') },
  ],
  gallery: [
    { title: 'Memory 1', caption: 'a little closer to you', image: publicPhoto("Screenshot 2026-09-09 at 11.31.35 PM.png"), rotation: '-2deg' },
    { title: 'Memory 2', caption: 'missing you, loving you', image: publicPhoto("Screenshot 2026-09-28 at 11.50.04 PM.png"), rotation: '2deg' },
    { title: 'Memory 3', caption: 'my favourite person', image: publicPhoto("Screenshot 2026-09-28 at 11.52.29 PM.png"), rotation: '-1deg' },
    { title: 'Memory 4', caption: 'a smile across the miles', image: publicPhoto("WhatsApp Image 2026-09-20 at 22.46.57.jpeg"), rotation: '3deg' },
    { title: 'Memory 5', caption: 'wish you were here', image: publicPhoto("WhatsApp Image 2026-10-03 at 19.15.55.jpeg"), rotation: '-2deg' },
    { title: 'Memory 6', caption: 'kept close, always', image: publicPhoto("WhatsApp Image 2026-10-03 at 19.15.56 (1).jpeg"), rotation: '2deg' },
    { title: 'Memory 8', caption: 'a little piece of us', image: publicPhoto("WhatsApp Image 2026-10-03 at 19.15.56.jpeg"), rotation: '3deg' },
    { title: 'Memory 11', caption: 'you make my day', image: publicPhoto("WhatsApp Image 2026-10-03 at 19.15.58 (1).jpeg"), rotation: '-1deg' },
    { title: 'Memory 18', caption: 'until our next hello', image: publicPhoto("WhatsApp Image 2026-10-03 at 19.23.14.jpeg"), rotation: '2deg' },
    { title: 'Memory 21', caption: 'thinking of you again', image: publicPhoto("WhatsApp Image 2026-10-03 at 19.42.42.jpeg"), rotation: '-2deg' },
    { title: 'Memory 22', caption: 'love, from wherever I am', image: publicPhoto("WhatsApp Image 2026-10-03 at 19.42.43 (1).jpeg"), rotation: '2deg' },
    { title: 'Memory 23', caption: 'saving this smile', image: publicPhoto("WhatsApp Image 2026-10-03 at 19.42.43.jpeg"), rotation: '-1deg' },
    { title: 'Memory 24', caption: 'all my love, right here', image: publicPhoto("WhatsApp Image 2026-10-03 at 19.42.44 (1).jpeg"), rotation: '3deg' },
    { title: 'Memory 25', caption: 'another reason to miss you', image: publicPhoto("WhatsApp Image 2026-10-03 at 19.42.44.jpeg"), rotation: '-2deg' },
    { title: 'Memory 26', caption: 'more of us, please', image: publicPhoto("WhatsApp Image 2026-10-03 at 19.42.45 (1).jpeg"), rotation: '2deg' },
    { title: 'Memory 27', caption: 'until I can hold you', image: publicPhoto("WhatsApp Image 2026-10-03 at 19.42.45.jpeg"), rotation: '-1deg' },
  ],
  letter: {
    eyebrow: '06 / what I wish I could say in person',
    title: 'A letter across the miles',
    greeting: 'My Manduuu,',
    paragraphs: [
      'I miss being close enough to hold your hand without thinking about the distance. I made this little surprise so you can feel how much you mean to me, even from here.',
      'Until I can hug you again, keep this as a little reminder: I love you, I miss you, and I’m looking forward to all the ordinary days we’ll get to share.',
    ],
    signoff: 'All my love, across every mile,',
    signature: 'your Brhama ♡',
  },
  keepsake: {
    image: { src: 'Opt2.png', alt: 'A little keepsake for my love' },
    quote: 'Until I can hold you again, let this little corner of us be a hug from me.',
    credit: 'for Manduuuuu❤️ by Brhama🕉️',
  },
} as const